apiVersion: v1
kind: ConfigMap

metadata:
  name: sso-backend-cfg

data:
  MODE: "prod"
  SERVICE_NAME: "sso"
  SERVER_SCHEME: "http"
  SERVER_DOMAIN: "localhost"
  SERVER_HTTP_PORT: "8080"
  SERVER_GRPC_PORT: "50050"
  SERVER_PROM_PORT: "8085"

  FRONTEND_PORT: "4000"

  POSTGRES_DB: "sso_db"
  POSTGRES_USER: "sso_owner"
  POSTGRES_PASSWORD: "794613825Zx!"
  POSTGRES_HOST: "postgres.default.svc.cluster.local"
  POSTGRES_PORT: "5432"

  JWT_SECRET: "supersecret"
  JWT_ISSUER: "SSO"
  ADMIN_USERS: "architect.lock@outlook.com"

  CAPTCHA_SITE_KEY: ""
  CAPTCHA_SECRET: ""

  OAUTH2_SUCCESS_URL: "http://localhost:3000/"
  OAUTH2_GOOGLE_CLIENT_ID: ""
  OAUTH2_GOOGLE_CLIENT_SECRET: ""
  OAUTH2_GOOGLE_REDIRECT_URL: "http://localhost:8080/api/auth/oauth2/google/callback"
  OAUTH2_GOOGLE_SCOPES: "https://www.googleapis.com/auth/userinfo.profile,https://www.googleapis.com/auth/userinfo.email"

  OIDC_SUCCESS_URL: "http://localhost:3000/"
  OIDC_GOOGLE_CLIENT_ID: ""
  OIDC_GOOGLE_CLIENT_SECRET: ""
  OIDC_GOOGLE_REDIRECT_URL: "http://localhost:8080/api/auth/oidc/google/callback"
  OIDC_GOOGLE_SCOPES: "openid,email,profile"

  WEBAUTHN_ORIGINS: "http://localhost,http://127.0.0.1,http://localhost:8080,http://localhost:3000"

  EMAIL_SERVER: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: ""
  EMAIL_PASS: ""
  EMAIL_ADMIN: ""

  MINIO_ADDR: "minio.default.svc.cluster.local:9000"
  MINIO_ROOT_USER: "admin"
  MINIO_ROOT_PASSWORD: "superstrongpassword"
  MINIO_BUCKET: "sso"
  MINIO_SSL: "false"

  REDIS_ADDR: "redis.default.svc.cluster.local:6379"
  REDIS_PASS: ""

  JAEGER_SAMPLER_TYPE: "const"
  JAEGER_SAMPLER_PARAM: "1"
  JAEGER_REPORTER_LOGSPANS: "true"
  JAEGER_REPORTER_LOCALAGENT: "localhost:6831"
  JAEGER_REPORTER_COLLECTOR: "http://localhost:14268/api/traces"
