linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10

linters:
  enable-all: true
  disable:
    - "varcheck"
    - "nosnakecase"
    - "maligned"
    - "structcheck"
    - "deadcode"
    - "scopelint"
    - "golint"
    - "exhaustivestruct"
    - "ifshort"
    - "interfacer"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  new-from-rev: HEAD
  new: true
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gofmt
