name: sso
services:
  redis:
    extends:
      file: compose-base.yaml
      service: redis
    volumes: !reset []

  db:
    extends:
      file: compose-base.yaml
      service: db
    volumes: !reset []

  backend:
    extends:
      file: compose-base.yaml
      service: backend
