serviceName: "sso"
srv_discovery:
  url: "http://localhost:50030"

server:
  mode: "dev"
  port: 50050
  scheme: "http"
  domain: "localhost"

auth:
  secret: "secret"

email:
  server: "smtp.gmail.com"
  port: 587
  user: "my@gmail.com"
  pass: "password"
  admin: "admin@gmail.com"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  database: "sso_db"

redis:
  addr: "localhost:6379"
  pass: ""

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "localhost:6831"