version: 3

tasks:
  run:
    desc: Run app
    cmds:
      - "go run cmd/main.go"

  pb:
    desc: Gen Proto file
    cmds:
      - "protoc --go_out=. --go-grpc_out=. --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative api/pb/sso.proto"

  mocks:
    desc: Generate mocks
    cmds:
      - mockgen -source="./internal/handler/grpc/grpc.go" -destination="mocks/mock_grpc_ctrl.go" -package=mocks
      - mockgen -source="./internal/controller/controller.go" -destination="mocks/mock_repos.go" -package=mocks
