version: 3

vars:
  DEV_ENV_FILE: "configs/envs/.env.dev"
  DEV_DOCKER_COMPOSE_PATH: "compose-dev.yaml"

  PROD_ENV_FILE: "configs/envs/.env.prod"
  PROD_DOCKER_COMPOSE_PATH: "compose-base.yaml"

  TEST_ENV_FILE: "configs/envs/.env.test"
  TEST_DOCKER_COMPOSE_PATH: "compose-test.yaml"

tasks:
  dc-dev:
    desc: Run dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_FILE}} -f {{.DEV_DOCKER_COMPOSE_PATH}} up --watch"

  dc-dev-build:
    desc: Run dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_FILE}} -f {{.DEV_DOCKER_COMPOSE_PATH}} up --build --watch"

  dc-dev-down:
    desc: Shutdown dev compose
    cmds:
      - "docker compose --env-file {{.DEV_ENV_FILE}} -f {{.DEV_DOCKER_COMPOSE_PATH}} down"

  dc-test:
    desc: Run integration tests helper containers
    cmds:
      - "docker compose --env-file {{.TEST_ENV_FILE}} -f {{.TEST_DOCKER_COMPOSE_PATH}} up"

  dc-test-down:
    desc: Shutdown integration tests helper containers
    cmds:
      - "docker compose -f {{.TEST_DOCKER_COMPOSE_PATH}} down"

  k-up:
    desc: Run k8s manifests
    cmds:
      - "kubectl apply -f backend/build/k8s/cfg/cfg.yaml"
      - "kubectl apply -f backend/build/k8s/svc.yaml"
      - "kubectl apply -f backend/build/k8s/deploy.yaml"

  k-down:
    desc: Remove k8s manifests
    cmds:
      - "kubectl delete -f backend/build/k8s/cfg/cfg.yaml"
      - "kubectl delete -f backend/build/k8s/svc.yaml"
      - "kubectl delete -f backend/build/k8s/deploy.yaml"