version: "2"
run:
  issues-exit-code: 1
  tests: false

linters:
  default: all
  disable:
    - wsl
    - depguard
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 10

  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: HEAD
  new: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test.go
