auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki

storage_config:
  filesystem:
    directory: /loki/chunks

limits_config:
  allow_structured_metadata: true

compactor:
  working_directory: /loki/compactor

schema_config:
  configs:
    - from: 2025-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h