apiVersion: v1
kind: Service

metadata:
  name: sso-frontend
  labels:
    app: sso-frontend

spec:
  selector:
    app: sso-frontend
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      nodePort: 30400

  type: NodePort