DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS permission CASCADE;
DROP TABLE IF EXISTS user_permission CASCADE;

DROP INDEX IF EXISTS users_id_idx CASCADE;
DROP INDEX IF EXISTS users_email_idx CASCADE;