import {Montserrat} from "next/font/google";
import "./globals.css";
import {Toaster} from "sonner"
import { ReCaptchaProvider } from "next-recaptcha-v3";
import Header from "../components/base/Header"
import {getRefreshToken, getSessionToken} from "../lib/auth/token"
import {AuthProvider} from "../providers/AuthProvider"

const Mont = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {
    return (
        <html lang="en">
            <body className={`${Mont.variable} ${Mont.className} antialiased overflow-x-hidden`}>
                <Toaster theme={"dark"}/>
                <AuthProvider>
                    <ReCaptchaProvider>
                        <Header/>
                        <div className={`-z-50 fixed`}>
                            <div className={`absolute bg-zinc-950/40 w-screen h-screen`}/>
                            <video loop muted autoPlay src={`/bg/vids/main3.mp4`} className={`object-cover w-screen h-screen`} />
                        </div>
                        {children}
                    </ReCaptchaProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
