// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/handler/grpc/grpc.go
//
// Generated by this command:
//
//	mockgen -source=./internal/handler/grpc/grpc.go -destination=mocks/mock_grpc_ctrl.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/JMURv/sso/pkg/model"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCtrl is a mock of Ctrl interface.
type MockCtrl struct {
	ctrl     *gomock.Controller
	recorder *MockCtrlMockRecorder
}

// MockCtrlMockRecorder is the mock recorder for MockCtrl.
type MockCtrlMockRecorder struct {
	mock *MockCtrl
}

// NewMockCtrl creates a new mock instance.
func NewMockCtrl(ctrl *gomock.Controller) *MockCtrl {
	mock := &MockCtrl{ctrl: ctrl}
	mock.recorder = &MockCtrlMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCtrl) EXPECT() *MockCtrlMockRecorder {
	return m.recorder
}

// CheckForgotPasswordEmail mocks base method.
func (m *MockCtrl) CheckForgotPasswordEmail(ctx context.Context, password string, uid uuid.UUID, code int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckForgotPasswordEmail", ctx, password, uid, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckForgotPasswordEmail indicates an expected call of CheckForgotPasswordEmail.
func (mr *MockCtrlMockRecorder) CheckForgotPasswordEmail(ctx, password, uid, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckForgotPasswordEmail", reflect.TypeOf((*MockCtrl)(nil).CheckForgotPasswordEmail), ctx, password, uid, code)
}

// CheckLoginCode mocks base method.
func (m *MockCtrl) CheckLoginCode(ctx context.Context, email string, code int) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckLoginCode", ctx, email, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckLoginCode indicates an expected call of CheckLoginCode.
func (mr *MockCtrlMockRecorder) CheckLoginCode(ctx, email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckLoginCode", reflect.TypeOf((*MockCtrl)(nil).CheckLoginCode), ctx, email, code)
}

// CreatePerm mocks base method.
func (m *MockCtrl) CreatePerm(ctx context.Context, req *model.Permission) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePerm", ctx, req)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePerm indicates an expected call of CreatePerm.
func (mr *MockCtrlMockRecorder) CreatePerm(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePerm", reflect.TypeOf((*MockCtrl)(nil).CreatePerm), ctx, req)
}

// CreateUser mocks base method.
func (m *MockCtrl) CreateUser(ctx context.Context, u *model.User, fileName string, bytes []byte) (uuid.UUID, string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, u, fileName, bytes)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockCtrlMockRecorder) CreateUser(ctx, u, fileName, bytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockCtrl)(nil).CreateUser), ctx, u, fileName, bytes)
}

// DeletePerm mocks base method.
func (m *MockCtrl) DeletePerm(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePerm", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePerm indicates an expected call of DeletePerm.
func (mr *MockCtrlMockRecorder) DeletePerm(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePerm", reflect.TypeOf((*MockCtrl)(nil).DeletePerm), ctx, id)
}

// DeleteUser mocks base method.
func (m *MockCtrl) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockCtrlMockRecorder) DeleteUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockCtrl)(nil).DeleteUser), ctx, userID)
}

// GetPermission mocks base method.
func (m *MockCtrl) GetPermission(ctx context.Context, id uint64) (*model.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", ctx, id)
	ret0, _ := ret[0].(*model.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockCtrlMockRecorder) GetPermission(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockCtrl)(nil).GetPermission), ctx, id)
}

// GetUserByEmail mocks base method.
func (m *MockCtrl) GetUserByEmail(ctx context.Context, email string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockCtrlMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockCtrl)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockCtrl) GetUserByID(ctx context.Context, userID uuid.UUID) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockCtrlMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockCtrl)(nil).GetUserByID), ctx, userID)
}

// GetUserByToken mocks base method.
func (m *MockCtrl) GetUserByToken(ctx context.Context, token string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByToken", ctx, token)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByToken indicates an expected call of GetUserByToken.
func (mr *MockCtrlMockRecorder) GetUserByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByToken", reflect.TypeOf((*MockCtrl)(nil).GetUserByToken), ctx, token)
}

// IsUserExist mocks base method.
func (m *MockCtrl) IsUserExist(ctx context.Context, email string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExist", ctx, email)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExist indicates an expected call of IsUserExist.
func (mr *MockCtrlMockRecorder) IsUserExist(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExist", reflect.TypeOf((*MockCtrl)(nil).IsUserExist), ctx, email)
}

// ListPermissions mocks base method.
func (m *MockCtrl) ListPermissions(ctx context.Context, page, size int) (*model.PaginatedPermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", ctx, page, size)
	ret0, _ := ret[0].(*model.PaginatedPermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockCtrlMockRecorder) ListPermissions(ctx, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockCtrl)(nil).ListPermissions), ctx, page, size)
}

// ListUsers mocks base method.
func (m *MockCtrl) ListUsers(ctx context.Context, page, size int) (*model.PaginatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, page, size)
	ret0, _ := ret[0].(*model.PaginatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockCtrlMockRecorder) ListUsers(ctx, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockCtrl)(nil).ListUsers), ctx, page, size)
}

// SearchUser mocks base method.
func (m *MockCtrl) SearchUser(ctx context.Context, query string, page, size int) (*model.PaginatedUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUser", ctx, query, page, size)
	ret0, _ := ret[0].(*model.PaginatedUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUser indicates an expected call of SearchUser.
func (mr *MockCtrlMockRecorder) SearchUser(ctx, query, page, size any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUser", reflect.TypeOf((*MockCtrl)(nil).SearchUser), ctx, query, page, size)
}

// SendForgotPasswordEmail mocks base method.
func (m *MockCtrl) SendForgotPasswordEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendForgotPasswordEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendForgotPasswordEmail indicates an expected call of SendForgotPasswordEmail.
func (mr *MockCtrlMockRecorder) SendForgotPasswordEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendForgotPasswordEmail", reflect.TypeOf((*MockCtrl)(nil).SendForgotPasswordEmail), ctx, email)
}

// SendLoginCode mocks base method.
func (m *MockCtrl) SendLoginCode(ctx context.Context, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendLoginCode", ctx, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendLoginCode indicates an expected call of SendLoginCode.
func (mr *MockCtrlMockRecorder) SendLoginCode(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendLoginCode", reflect.TypeOf((*MockCtrl)(nil).SendLoginCode), ctx, email, password)
}

// SendSupportEmail mocks base method.
func (m *MockCtrl) SendSupportEmail(ctx context.Context, uid uuid.UUID, theme, text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendSupportEmail", ctx, uid, theme, text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendSupportEmail indicates an expected call of SendSupportEmail.
func (mr *MockCtrlMockRecorder) SendSupportEmail(ctx, uid, theme, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendSupportEmail", reflect.TypeOf((*MockCtrl)(nil).SendSupportEmail), ctx, uid, theme, text)
}

// UpdatePerm mocks base method.
func (m *MockCtrl) UpdatePerm(ctx context.Context, id uint64, req *model.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePerm", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePerm indicates an expected call of UpdatePerm.
func (mr *MockCtrlMockRecorder) UpdatePerm(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePerm", reflect.TypeOf((*MockCtrl)(nil).UpdatePerm), ctx, id, req)
}

// UpdateUser mocks base method.
func (m *MockCtrl) UpdateUser(ctx context.Context, id uuid.UUID, req *model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockCtrlMockRecorder) UpdateUser(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockCtrl)(nil).UpdateUser), ctx, id, req)
}

// ValidateToken mocks base method.
func (m *MockCtrl) ValidateToken(ctx context.Context, token string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockCtrlMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockCtrl)(nil).ValidateToken), ctx, token)
}
