mode: "dev"
serviceName: "sso"

auth:
  secret: "DYHlaJpPiZ"
  providerSignSecret: "DYHlaJpPiZ"
  admins: [
    "architect.lock@outlook.com"
  ]

  captcha:
    sitekey: ""
    secret: ""

  ouath:
    successURL: "http://localhost:3000/"
    google:
      clientID: "id"
      clientSecret: "secret"
      redirectURL: "http://localhost:8080/api/auth/google/callback"
      scopes: [
        "https://www.googleapis.com/auth/userinfo.profile",
        "https://www.googleapis.com/auth/userinfo.email"
      ]
  oidc:
    successURL: "http://localhost:3000/"
    google:
      clientID: "id"
      clientSecret: "secret"
      redirectURL: "http://localhost:8080/api/auth/oidc/google/callback"
      scopes: ["openid","email","profile"]

server:
  port: 8080
  grpc_port: 50065
  scheme: "http"
  domain: "localhost"

email:
  server: "smtp.gmail.com"
  port: 587
  user: "my@gmail.com"
  pass: "password"
  admin: "admin@gmail.com"

db:
  host: "localhost"
  port: 5432
  user: "sso_owner"
  password: "app_password"
  database: "sso_db"

minio:
  addr: "localhost:9000"
  public_addr: "http://localhost:9000"
  access_key: "minio"
  secret_key: "minio123"
  bucket: "sso"
  use_ssl: false

redis:
  addr: "localhost:6379"
  pass: ""

prometheus:
  port: 9000

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    LogSpans: true
    LocalAgentHostPort: "localhost:6831"
    CollectorEndpoint: "http://localhost:14268/api/traces"