mode: "dev"
service_name: "sso"

auth:
  secret: ""
  provider_sign_secret: ""
  admins: [
    ""
  ]

  captcha:
    site_key: ""
    secret: ""

  oauth:
    success_url: "http://localhost:3000/"
    google:
      client_id: ""
      client_secret: ""
      redirect_url: "http://localhost:8080/api/auth/oauth2/google/callback"
      scopes: [
        "https://www.googleapis.com/auth/userinfo.profile",
        "https://www.googleapis.com/auth/userinfo.email"
      ]

  oidc:
    success_url: "http://localhost:3000/"
    google:
      client_id: ""
      client_secret: ""
      redirect_url: "http://localhost:8080/api/auth/oidc/google/callback"
      scopes: [ "openid", "email", "profile" ]

server:
  port: 8080
  grpc_port: 50050
  scheme: "http"
  domain: "localhost"

email:
  server: "smtp.gmail.com"
  port: 587
  user: ""
  pass: ""
  admin: ""

db:
  host: "db"
  port: 5432
  user: "sso_owner"
  password: "794613825Zx!"
  database: "sso_db"

minio:
  addr: "minio:9000"
  access_key: "admin"
  secret_key: "superstrongpassword"
  bucket: "sso"
  use_ssl: false

redis:
  addr: "redis:6379"
  pass: ""

prometheus:
  port: 9005

jaeger:
  sampler:
    type: "const"
    param: 1
  reporter:
    log_spans: true
    local_agent_host_port: "jaeger:6831"
    collector_endpoint: "http://jaeger:14268/api/traces"