on:
  push:
    branches: [main, master]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
