on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'

      - name: Log in to Docker Hub
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: echo "${PASSWORD}" | docker login --username "${USERNAME}" --password-stdin

      - name: Build and push Docker image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          docker build --no-cache -t ${USERNAME}/${IMAGE_NAME}:latest .
          docker push ${USERNAME}/${IMAGE_NAME}:latest

      - name: Run Docker container (optional)
        env:
          USERNAME: ${{ secrets.USERNAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
        run: |
          docker run -d -p 50050:50050 ${USERNAME}/${IMAGE_NAME}:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.4'

      - name: Install dependencies
        run: go mod tidy

      - name: Install gocovmerge
        run: go install github.com/wadey/gocovmerge@latest

      - name: Run repository tests
        run: go test -coverprofile=repo_coverage.out ./internal/db/repository

      - name: Run controller tests
        run: go test -coverprofile=ctrl_coverage.out ./internal/controller

      - name: Run handler tests
        run: go test -coverprofile=hdl_coverage.out ./internal/handler/grpc

      - name: Merge coverage reports
        run: gocovmerge repo_coverage.out ctrl_coverage.out hdl_coverage.out > coverage.out

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: coverage.out
          report: true
          chart: true
          amend: true
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'
        continue-on-error: true