on:
  push:
    branches: [main, master]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push backend Docker image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BACKEND_IMAGE_NAME: ${{ secrets.BACKEND_IMAGE_NAME }}
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: build/docker/Dockerfile
          push: true
          tags: |
            ${{ secrets.USERNAME }}/${{ secrets.BACKEND_IMAGE_NAME }}:latest

      - name: Build and push frontend Docker image
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          FRONTEND_IMAGE_NAME: ${{ secrets.FRONTEND_IMAGE_NAME }}
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.USERNAME }}/${{ secrets.FRONTEND_IMAGE_NAME }}:latest
