on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.1'

      - name: Install dependencies
        run: go mod tidy

      - name: Install gocovmerge
        run: go install github.com/wadey/gocovmerge@latest

      - name: Run repository tests
        run: go test -coverprofile=repo_coverage.out ./internal/repository/db

      - name: Run controller tests
        run: go test -coverprofile=ctrl_coverage.out ./internal/controller

      - name: Run handler tests
        run: go test -coverprofile=hdl_coverage.out ./internal/handler/grpc

      - name: Merge coverage reports
        run: gocovmerge repo_coverage.out ctrl_coverage.out hdl_coverage.out > coverage.out

      - name: Update coverage report
        uses: ncruces/go-coverage-report@v0
        with:
          coverage-file: coverage.out
          report: true
          chart: true
          amend: true
        if: |
          matrix.os == 'ubuntu-latest' &&
          github.event_name == 'push'
        continue-on-error: true